version: '3'
services:
  notebook:
    container_name: prasc_notebook
    ports: ["8888:8888"]
    volumes:
      - './data:/home/jovyan/work'
    image: prasc_rle
    command: "jupyter notebook --port=8888 --no-browser --NotebookApp.token='' --NotebookApp.password=''"

